# Generated by Django 5.2 on 2025-04-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkouts', '0003_order_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paypal_payment',
        ),
    ]
